# Generated by Django 5.1 on 2024-08-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
